name: gin_env
channels:
  - conda-forge
  - pytorch
dependencies:
 - python=3.11
 - pytorch
 - scipy
 - pip: 
    - torch-geometric
    - rdkit
    - mlflow
    - scikit-learn
    - pandas
    - numpy
    - azureml-mlflow
    - matplotlib
    - networkx